pr:
  branches:
    include:
      - qa
      - dev

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted agent

variables:
  SONAR_PROJECT_KEY: "TravelYaari"
  SONAR_ORG: "radhaigude"

stages:
  - stage: BuildAndScan
    displayName: "Build & SonarCloud Scan"
    jobs:
      - job: ScanJob
        displayName: "Scan Job"
        steps:
          # Checkout code
          - checkout: self

          # Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          # Install dependencies
          - script: npm install
            displayName: 'Install Dependencies'

          # Prepare SonarCloud Analysis
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'SonarQube-Service-Connection1'  # Service connection name
              organization: $(SONAR_ORG)
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: $(SONAR_PROJECT_KEY)
              cliProjectName: $(SONAR_PROJECT_KEY)
              extraProperties: |
                sonar.sources=.
                sonar.tests=.
                sonar.test.inclusions=**/*.spec.js,**/*.test.js
                sonar.javascript.lcov.reportPaths=coverage/lcov.info
            displayName: 'Prepare SonarCloud Analysis'

          # Build the project
          - script: npm run build
            displayName: 'Build Project'

          # Run SonarCloud Analysis
          - task: SonarCloudAnalyze@1
            displayName: 'Run SonarCloud Analysis'

          # Publish & enforce quality gate
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
            displayName: 'Publish & Enforce Quality Gate'
